from pynput import mouse, keyboard
from random import uniform
from time import sleep
Keyboard = keyboard.Controller()
Mouse = mouse.Controller()


while True:
    Keyboard.press("w")
    Keyboard.press("a")
    sleep(uniform(1, 5))
    Keyboard.release("a")
    Keyboard.press(keyboard.Key.enter)
    sleep(0.1 * uniform(2, 4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 2))
    Keyboard.press(keyboard.Key.enter)
    sleep(uniform(0.2, 0.4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 2))
    Keyboard.press(keyboard.Key.enter)
    sleep(uniform(0.2, 0.4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 3))
    Keyboard.press("d")
    sleep(uniform(1, 3))
    Keyboard.release("w")
    sleep(uniform(1, 3))
    Keyboard.release("d")
    sleep(uniform(1, 5))
    Keyboard.press(keyboard.Key.enter)
    sleep(0.1 * uniform(2, 4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 2))
    Keyboard.press(keyboard.Key.enter)
    sleep(uniform(0.2, 0.4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 2))
    Keyboard.press(keyboard.Key.enter)
    sleep(uniform(0.2, 0.4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 2))
    Keyboard.press(keyboard.Key.enter)
    sleep(uniform(0.2, 0.4))
    Keyboard.release(keyboard.Key.enter)
    sleep(uniform(1, 2))
    Mouse.click(mouse.Button.right)
