from pynput import mouse, keyboard
from random import randint
from time import sleep
Keyboard = keyboard.Controller()
Mouse = mouse.Controller()
while True:
    Keyboard.press("w")
    Keyboard.press("a")
    sleep(randint(1, 5))
    Keyboard.release("a")
    sleep(randint(1, 3))
    Keyboard.press("d")
    sleep(randint(1, 3))
    Keyboard.release("w")
    sleep(randint(1, 3))
    Keyboard.release("d")
    sleep(randint(1, 5))
    Keyboard.press(keyboard.Key.enter)
    sleep(0.1 * randint(2, 4))
    Keyboard.release(keyboard.Key.enter)
    sleep(randint(2, 4))
    Keyboard.press(keyboard.Key.enter)
    sleep(0.1 * randint(2, 4))
    Keyboard.release(keyboard.Key.enter)
    sleep(randint(2, 4))
    Keyboard.press(keyboard.Key.enter)
    sleep(0.1 * randint(2, 4))
    Keyboard.release(keyboard.Key.enter)
    sleep(randint(1, 4))
    Mouse.click(mouse.Button.right)
